default: &default
  adapter: postgresql
  port: 5432
  host: localhost
  template: template0
  reconnect: true
  encoding: utf8
  username: postgres
  password: postgrespw

development:
  <<: *default
  database: rails_grape_dev
